// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8nADLvCB6-MHSqzew9OJh1ymEgB7mAYk',
    appId: '1:991973302992:web:c44220ebfdaf145db074d5',
    messagingSenderId: '991973302992',
    projectId: 'gestionhopitalapp',
    authDomain: 'gestionhopitalapp.firebaseapp.com',
    storageBucket: 'gestionhopitalapp.firebasestorage.app',
    measurementId: 'G-K00CHGHB09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWHPW7ZOPYfoPWNyeun4VI7wXct8gdTgg',
    appId: '1:991973302992:android:615d22a9249c6c2cb074d5',
    messagingSenderId: '991973302992',
    projectId: 'gestionhopitalapp',
    storageBucket: 'gestionhopitalapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ0znbGp6mxWmZEEaRFte4D7-VUrtbNVA',
    appId: '1:991973302992:ios:ddd00b3100a98667b074d5',
    messagingSenderId: '991973302992',
    projectId: 'gestionhopitalapp',
    storageBucket: 'gestionhopitalapp.firebasestorage.app',
    iosBundleId: 'com.example.gestionProduit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ0znbGp6mxWmZEEaRFte4D7-VUrtbNVA',
    appId: '1:991973302992:ios:ddd00b3100a98667b074d5',
    messagingSenderId: '991973302992',
    projectId: 'gestionhopitalapp',
    storageBucket: 'gestionhopitalapp.firebasestorage.app',
    iosBundleId: 'com.example.gestionProduit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8nADLvCB6-MHSqzew9OJh1ymEgB7mAYk',
    appId: '1:991973302992:web:a8b309ff9982d55bb074d5',
    messagingSenderId: '991973302992',
    projectId: 'gestionhopitalapp',
    authDomain: 'gestionhopitalapp.firebaseapp.com',
    storageBucket: 'gestionhopitalapp.firebasestorage.app',
    measurementId: 'G-10YY4ME86B',
  );
}
